import React, { useMemo, useState } from 'react';

const categories = [
  { id:'bangles', label:'Bangles', icon:'◌', tone:'blush', copy:'Stackable, sculptural and made to move with you.' },
  { id:'necklaces', label:'Necklaces', icon:'♢', tone:'sand', copy:'Quiet statements for unforgettable moments.' },
  { id:'earrings', label:'Earrings', icon:'◈', tone:'lavender', copy:'A little light for every look.' },
  { id:'rings', label:'Rings', icon:'✦', tone:'sage', copy:'Everyday symbols of your own story.' },
  { id:'payals', label:'Payals', icon:'⌁', tone:'blue', copy:'Delicate music with every step.' }
];
const adjectives = ['Celeste','Mira','Solenne','Aurelia','Noor','Luna','Elara','Amara','Iris','Siena','Veda','Opal'];
const materials = ['18k Gold','Rose Gold','925 Silver','Diamond Vermeil'];
const products = categories.flatMap((cat, categoryIndex) => adjectives.map((name, i) => ({
  id:`${cat.id}-${i+1}`, category:cat.id, name:`${name} ${cat.label.slice(0,-1)}`, price: [189,245,320,410,520][(i+categoryIndex)%5] * (categoryIndex===1 ? 2 : 1), material:materials[(i+categoryIndex)%materials.length], badge:i===0?'Bestseller':i===3?'New':'', art:['gold','pearl','rose','silver','amber'][(i+categoryIndex)%5], symbol:cat.icon
})));

function Header({ cartCount, onNavigate, onCategory, menuOpen, setMenuOpen }) {
  return <><div className="announcement">Complimentary gift wrapping on orders over $150 <span>✦</span> Free worldwide shipping</div><header className="header"><button className="menu-btn" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle menu">☰</button><button className="wordmark" onClick={()=>onNavigate('home')}>AURUM <i>&</i> CO.</button><nav className={menuOpen?'nav open':'nav'}><button onClick={()=>onNavigate('shop')}>Shop all</button>{categories.map(c=><button key={c.id} onClick={()=>onCategory(c.id)}>{c.label}</button>)}<button onClick={()=>onNavigate('about')}>Our story</button></nav><div className="header-actions"><button aria-label="Search" onClick={()=>onNavigate('shop')}>⌕</button><button aria-label="Shopping bag" onClick={()=>onNavigate('cart')}>Bag <b>{cartCount}</b></button></div></header></>;
}
function ProductCard({ product, addToCart }) { return <article className="product-card"><div className={`product-art ${product.art}`}><span className="product-symbol">{product.symbol}</span>{product.badge&&<span className="badge">{product.badge}</span>}<button className="heart" aria-label="Add to wishlist">♡</button></div><div className="product-info"><div><h3>{product.name}</h3><p>{product.material}</p></div><strong>${product.price}</strong></div><button className="add-btn" onClick={()=>addToCart(product)}>Add to bag <span>+</span></button></article> }
function Pagination({ page, pages, setPage }) { return <div className="pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>←</button>{Array.from({length:pages},(_,i)=><button className={page===i+1?'active':''} key={i} onClick={()=>setPage(i+1)}>{String(i+1).padStart(2,'0')}</button>)}<button disabled={page===pages} onClick={()=>setPage(page+1)}>→</button></div> }
function Home({ onCategory, onNavigate, addToCart }) { return <main><section className="hero"><div className="hero-copy"><p className="eyebrow">THE NEW HEIRLOOMS · EST. 1987</p><h1>Jewellery<br/><em>with a soul.</em></h1><p className="hero-text">Pieces designed to become part of your story — treasured today, passed on tomorrow.</p><button className="button dark" onClick={()=>onNavigate('shop')}>Discover the collection <span>↗</span></button></div><div className="hero-orbit"><div className="orbit-ring ring-one"></div><div className="orbit-ring ring-two"></div><div className="hero-gem">✦<small>18K</small></div><p>HAND-FINISHED<br/><b>IN OUR ATELIER</b></p></div></section><section className="section categories"><div className="section-heading"><div><p className="eyebrow">SHOP BY FORM</p><h2>Find your <em>signature.</em></h2></div><button className="text-link" onClick={()=>onNavigate('shop')}>View all pieces ↗</button></div><div className="category-grid">{categories.map(c=><button className={`category-card ${c.tone}`} key={c.id} onClick={()=>onCategory(c.id)}><span>{c.icon}</span><h3>{c.label}</h3><p>{c.copy}</p><b>Explore {c.label} ↗</b></button>)}</div></section><section className="editorial"><div><p className="eyebrow">THE EVERYDAY EDIT</p><h2>Little luxuries.<br/><em>Big feeling.</em></h2><p>There is beauty in the pieces you reach for without thinking. Our everyday collection is designed for exactly that.</p><button className="button light" onClick={()=>onNavigate('shop')}>Shop everyday</button></div><div className="editorial-art"><span>✧</span><p>AURUM<br/><small>COLLECTION 01</small></p></div></section><section className="section"><div className="section-heading"><div><p className="eyebrow">MOST LOVED</p><h2>Made to be <em>remembered.</em></h2></div></div><div className="product-grid">{products.slice(0,4).map(p=><ProductCard key={p.id} product={p} addToCart={addToCart}/>)}</div></section></main> }
function Shop({ selectedCategory, addToCart }) { const [page,setPage]=useState(1); const [query,setQuery]=useState(''); const cat=categories.find(c=>c.id===selectedCategory); const filtered=useMemo(()=>products.filter(p=>(!selectedCategory||p.category===selectedCategory)&&p.name.toLowerCase().includes(query.toLowerCase())),[selectedCategory,query]); const pageSize=8; const pages=Math.max(1,Math.ceil(filtered.length/pageSize)); const visible=filtered.slice((page-1)*pageSize,page*pageSize); return <main className="shop-page"><div className="shop-hero"><p className="eyebrow">{cat?'THE '+cat.label.toUpperCase():'THE COMPLETE COLLECTION'}</p><h1>{cat?cat.label:'All pieces'} <em>for all seasons.</em></h1><p>{cat?cat.copy:'Thoughtfully made jewellery, designed to be worn often and loved forever.'}</p></div><div className="shop-toolbar"><div className="tabs"><button className={!selectedCategory?'selected':''} onClick={()=>window.dispatchEvent(new CustomEvent('category',{detail:null}))}>All</button>{categories.map(c=><button className={selectedCategory===c.id?'selected':''} key={c.id} onClick={()=>window.dispatchEvent(new CustomEvent('category',{detail:c.id}))}>{c.label}</button>)}</div><label className="search">⌕ <input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search pieces..."/></label></div>{visible.length?<div className="product-grid">{visible.map(p=><ProductCard key={p.id} product={p} addToCart={addToCart}/>)}</div>:<div className="empty"><span>✧</span><h2>No pieces found</h2><p>Try another search or explore the full collection.</p></div>}<Pagination page={Math.min(page,pages)} pages={pages} setPage={setPage}/></main> }
function Cart({ cart, setCart, onNavigate }) { const total=cart.reduce((sum,p)=>sum+p.price*p.quantity,0); return <main className="cart-page"><p className="eyebrow">YOUR SELECTION</p><h1>Shopping <em>bag.</em></h1>{!cart.length?<div className="empty"><span>♡</span><h2>Your bag is waiting</h2><p>Discover something beautiful to make it yours.</p><button className="button dark" onClick={()=>onNavigate('shop')}>Explore jewellery</button></div>:<div className="cart-layout"><div>{cart.map(p=><div className="cart-item" key={p.id}><div className={`mini-art ${p.art}`}>{p.symbol}</div><div><h3>{p.name}</h3><p>{p.material}</p><div className="quantity"><button onClick={()=>setCart(cart.map(x=>x.id===p.id?{...x,quantity:Math.max(1,x.quantity-1)}:x))}>−</button>{p.quantity}<button onClick={()=>setCart(cart.map(x=>x.id===p.id?{...x,quantity:x.quantity+1}:x))}>+</button></div></div><strong>${p.price*p.quantity}</strong><button className="remove" onClick={()=>setCart(cart.filter(x=>x.id!==p.id))}>×</button></div>)}</div><aside className="summary"><p className="eyebrow">ORDER SUMMARY</p><div><span>Subtotal</span><b>${total}</b></div><div><span>Shipping</span><b>Complimentary</b></div><hr/><div className="total"><span>Total</span><b>${total}</b></div><button className="button dark full" onClick={()=>alert('Thank you! Checkout will be connected to your preferred payment provider.')}>Continue to checkout <span>↗</span></button></aside></div>}</main> }
export default function App(){ const [view,setView]=useState('home'); const [selectedCategory,setSelectedCategory]=useState(null); const [cart,setCart]=useState([]); const [menuOpen,setMenuOpen]=useState(false); React.useEffect(()=>{const fn=e=>{setSelectedCategory(e.detail);setView('shop');window.scrollTo(0,0)};window.addEventListener('category',fn);return()=>window.removeEventListener('category',fn)},[]); const navigate=v=>{setView(v);setMenuOpen(false);window.scrollTo(0,0)}; const category=id=>{setSelectedCategory(id);navigate('shop')}; const addToCart=p=>setCart(c=>c.some(x=>x.id===p.id)?c.map(x=>x.id===p.id?{...x,quantity:x.quantity+1}:x):[...c,{...p,quantity:1}]); return <><Header cartCount={cart.reduce((s,p)=>s+p.quantity,0)} onNavigate={navigate} onCategory={category} menuOpen={menuOpen} setMenuOpen={setMenuOpen}/>{view==='home'&&<Home onCategory={category} onNavigate={navigate} addToCart={addToCart}/>} {view==='shop'&&<Shop selectedCategory={selectedCategory} addToCart={addToCart}/>} {view==='cart'&&<Cart cart={cart} setCart={setCart} onNavigate={navigate}/>} {view==='about'&&<section className="about"><p className="eyebrow">OUR STORY</p><h1>Made slowly.<br/><em>Worn forever.</em></h1><p>From a small family atelier to your jewellery box, Aurum & Co. is a celebration of craft, character and the everyday rituals that make life radiant.</p></section>}<footer><button className="wordmark" onClick={()=>navigate('home')}>AURUM <i>&</i> CO.</button><p>Fine jewellery for every chapter.</p><span>© 2025 Aurum & Co.</span></footer></> }
